'use strict';
const $=id=>document.getElementById(id);
const zones={
 teams:{name:'团队创作区',color:'#d4a566',description:'25 个四人工位作为持续使用的工作基地。按团队编号定位，集中开发、导师巡回和成果展示都围绕这些工位展开。',note:'100 人仅为参赛者计划规模；工位能否放下需依据现场尺寸复核。'},
 stage:{name:'舞台与演示区',color:'#718d94',description:'在球场一端设置屏幕、主持位置与演示台，开场和路演共用。屏幕朝向工位和看台，音量随活动阶段调整。',note:'远端有篮架和窗面；篮架处理、投影遮光与实际通道需现场确认。'},
 mentors:{name:'导师咨询区',color:'#cba177',description:'靠近团队区安排预约式咨询。用短时段门诊减少围堵，导师也可沿主通道巡回，意见带回各队工位实施。',note:'示意为 2 个咨询点；导师人数与咨询轮次需要另行安排。'},
 quiet:{name:'安静缓冲区',color:'#a5b596',description:'在远离签到和茶歇的一侧安排短时安静座位，用于独立思考、临时交流与情绪缓冲。',note:'开放式体育馆难以完全隔声；这一分区不代表可在场内过夜。'},
 checkin:{name:'签到与服务台',color:'#bca783',description:'靠近拟设入口集中处理签到、队伍指引与物资领取。活动开始后继续作为帮助台和失物招领点。',note:'照片未显示全部出入口，入口与签到位置仅为示意，需按实际位置调整。'},
 break:{name:'茶歇与交流区',color:'#c4a886',description:'设置饮水与短暂停留的位置，茶歇与电脑工位保持分离，让临时交流在边缘区域发生。',note:'需确认场馆对餐饮、清洁和垃圾收集的要求。'},
 aisle:{name:'连续通道',color:'#95b9ad',description:'用中央通道与外围联系通道串联工位、舞台和服务区。把临时展架、行李和线缆安排在通道之外。',note:'动线用于说明组织方式，宽度、疏散安排和入口位置尚未测量核定。'},
 stands:{name:'既有看台',color:'#659585',description:'优先利用现有看台承接开场、观看路演和短时观众停留，减少工位区在活动中的反复搬动。',note:'需确认看台可开放范围、视线和可用座位；图中座位不代表核定容量。'}
};
const phases=[
 {start:0,end:3,id:'opening',label:'签到开场',title:'签到、相遇与开场',focus:'签到台 → 看台 → 团队工位',description:'参与者完成签到，在看台集中听取题目与安排，随后按队伍编号找到各自的创作基地。',actions:['入口服务台分流签到与领物。','使用舞台与既有看台完成开场。','队伍就位，确认网络与设备可用。']},
 {start:3,end:12,id:'build',label:'选题开发',title:'想法落到第一版',focus:'团队工位 · 流动导师',description:'把主要空间交给团队。舞台暂停连续扩音，导师通过预约和巡回帮助团队收敛问题。',actions:['团队完成问题定义与任务分工。','在工位开展讨论、设计与开发。','把高声讨论引导至交流区。']},
 {start:12,end:24,id:'build',label:'原型与轮休',title:'让原型跑起来',focus:'团队工位 · 安静缓冲区',description:'进入持续开发阶段，安排成员轮换休息。场内安静区用于短时缓冲，实际过夜和休息空间另行确认。',actions:['完成最小可运行原型。','降低公共广播频率，集中发布通知。','安排人员轮休与夜间值守。']},
 {start:24,end:30,id:'mentoring',label:'导师反馈',title:'带着问题见导师',focus:'导师咨询区 · 各团队工位',description:'用预约时段集中开展导师门诊。每队带着可演示的原型与具体问题前来，带着修改清单返回。',actions:['每队准备一个原型和一个关键问题。','错峰咨询，避免队伍聚集等待。','记录建议，在工位完成下一轮迭代。']},
 {start:30,end:42,id:'build',label:'迭代测试',title:'从能运行，到能讲清',focus:'团队工位 · 演示测试台',description:'团队完善作品、测试真实使用流程并准备路演。舞台端按预约做设备与演示检查。',actions:['邀请其他团队互相试用。','检查网络依赖和备用演示材料。','按次序完成投屏与音频检查。']},
 {start:42,end:47,id:'demo',label:'项目路演',title:'让作品被看见',focus:'舞台 · 看台 · 项目展示',description:'观众进入看台，参赛队按顺序演示。团队桌面保留为作品体验点，便于路演后继续交流。',actions:['主持、评委与演示队伍按顺序到位。','主通道保持可通行。','路演后在团队工位体验作品。']},
 {start:47,end:48.01,id:'closing',label:'收尾离场',title:'把成果与场地都交好',focus:'舞台 → 工位 → 服务台',description:'完成总结和成果归档，各队整理设备、垃圾与个人物品，分批离场并完成场馆交接。',actions:['提交成果链接与团队信息。','检查工位、归还物资并清点设备。','工作人员复核场地后完成交接。']}
];
let renderer,hours=0,playing=false,lastFrame=0,currentPhase=-1,selectedZone='teams';
function zone(id){if(!zones[id])return;selectedZone=id;renderer?.setSelectedZone(id);const z=zones[id];$('zone-name').textContent=z.name;$('zone-description').textContent=z.description;$('zone-note').textContent=z.note;$('zone-dot').style.background=z.color;document.querySelectorAll('#zone-legend button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.zone===id)));}
for(const [id,z] of Object.entries(zones)){const b=document.createElement('button');b.type='button';b.dataset.zone=id;b.setAttribute('aria-pressed','false');const dot=document.createElement('span');dot.className='zone-dot';dot.style.background=z.color;b.append(dot,document.createTextNode(z.name));b.addEventListener('click',()=>zone(id));$('zone-legend').append(b);}
for(const [i,p] of phases.entries()){const b=document.createElement('button');b.type='button';b.dataset.phase=i;b.innerHTML=`<span>T + ${String(p.start).padStart(2,'0')} h</span>${p.label}`;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{setPlaying(false);setTime(p.start);});$('milestones').append(b);}
function setTime(value){hours=Math.max(0,Math.min(48,Number(value)));$('timeline').value=hours;const totalMinutes=Math.round(hours*60);$('phase-time').textContent=`T + ${String(Math.floor(totalMinutes/60)).padStart(2,'0')}:${String(totalMinutes%60).padStart(2,'0')}`;const index=phases.findIndex(p=>hours>=p.start&&hours<p.end);const p=phases[index];if(index!==currentPhase){currentPhase=index;$('phase-title').textContent=p.title;$('phase-description').textContent=p.description;$('phase-focus').textContent=p.focus;$('phase-actions').replaceChildren(...p.actions.map(a=>{const li=document.createElement('li');li.textContent=a;return li;}));document.querySelectorAll('#milestones button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.phase)===index)));renderer?.setPhase(p.id);}renderer?.setTime(hours);}
function setPlaying(value){playing=value;$('play').textContent=playing?'Ⅱ 暂停活动流程':'▶ 播放活动流程';$('play').setAttribute('aria-pressed',String(playing));renderer?.setPlaying(playing);}
$('play').addEventListener('click',()=>{if(hours>=48)setTime(0);setPlaying(!playing);});$('timeline').addEventListener('input',e=>{setPlaying(false);setTime(e.target.value);});
function setView(name){renderer?.setView(name);for(const id of ['perspective','top','walk'])$(id).setAttribute('aria-pressed',String(name===id));$('roof').checked=name==='walk';renderer?.setRoof($('roof').checked);}
$('perspective').addEventListener('click',()=>setView('perspective'));$('top').addEventListener('click',()=>setView('top'));$('walk').addEventListener('click',()=>setView('walk'));$('reset').addEventListener('click',()=>{renderer?.reset();setView('walk');zone(selectedZone);});$('flows').addEventListener('change',e=>renderer?.setFlows(e.target.checked));$('roof').addEventListener('change',e=>renderer?.setRoof(e.target.checked));
$('reference').addEventListener('click',()=>{setPlaying(false);$('photo-dialog').showModal();});$('close-photo').addEventListener('click',()=>$('photo-dialog').close());$('assets-open').addEventListener('click',()=>{setPlaying(false);$('assets-dialog').showModal();});$('close-assets').addEventListener('click',()=>$('assets-dialog').close());for(const id of ['photo-dialog','assets-dialog'])$(id).addEventListener('click',e=>{if(e.target===$(id)){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function planText(){return `# 体育馆黑客松空间与时间概念方案\n\n## 任务假设\n\n100名参赛者，25队，每队4人，48小时。导师、评委与工作人员另计。\n照片可见绿色球场、两侧看台、钢架屋顶和窗面；模型比例为示意，无实测尺寸。\n\n## 空间规划\n\n${Object.values(zones).map(z=>`### ${z.name}\n\n${z.description}\n\n待确认：${z.note}`).join('\n\n')}\n\n## 48小时流程\n\n${phases.map(p=>`### T+${p.start}–${Math.min(48,p.end)} h：${p.title}\n\n${p.description}\n\n${p.actions.map(a=>'- '+a).join('\n')}`).join('\n\n')}\n\n## 实施前现场确认\n\n可用尺寸与全体出入口、篮架移动条件、场馆开放时段、电力与网络承载、休息安排、看台可用范围、工作人员和导师人数。\n\n此方案用于活动组织讨论，不代表施工图、容量核定或人流仿真结果。\n`;}
$('download').addEventListener('click',()=>{const blob=new Blob([planText()],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='体育馆黑客松-100人48小时概念方案.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);$('toast').hidden=false;$('toast').textContent='方案已生成，可在下载中查看';setTimeout(()=>$('toast').hidden=true,3500);});
function tick(now){const dt=lastFrame?Math.min((now-lastFrame)/1000,.1):0;lastFrame=now;if(playing&&!document.hidden&&!$('photo-dialog').open){setTime(hours+dt*1.5);if(hours>=48)setPlaying(false);}requestAnimationFrame(tick);}
const assetLabels={table:'团队会议桌',chair:'活动座椅',laptop:'笔记本电脑',plant:'场馆绿植',speaker:'舞台音箱'};
function modelStatus(status){const el=$('asset-state');el.dataset.state=status.state;el.dataset.loaded=String(status.loaded??0);el.dataset.total=String(status.total??0);if(status.state==='ready'){el.textContent=`3DAssets · ${status.loaded}/${status.total} 款模型已载入`;$('loading').hidden=true;}else if(status.state==='partial'){el.textContent=`已载入 ${status.loaded}/${status.total} 款 · 部分模型加载失败`;$('loading').hidden=true;}else if(status.state==='error'){el.textContent='模型加载失败';$('loading').hidden=false;$('loading').textContent='场景加载失败，请刷新页面重试。';}else{el.textContent=`正在加载模型 ${status.loaded??0}/${status.total||'…'}`;}}
async function showAssetSources(){try{const response=await fetch('assets/catalogue.json');if(!response.ok)throw new Error('Catalogue HTTP '+response.status);const catalogue=await response.json();for(const asset of catalogue.assets){const card=document.createElement('article');card.className='asset-card';const name=document.createElement('strong');name.textContent=assetLabels[asset.role]||asset.title;const meta=document.createElement('span');meta.textContent=`${asset.title} · ${(asset.bytes/1024).toFixed(0)} KB · CC0`;const links=document.createElement('div');const source=document.createElement('a');source.href=asset.sourceUrl;source.target='_blank';source.rel='noopener noreferrer';source.textContent='查看来源 ↗';const file=document.createElement('a');file.href=asset.localPath;file.download=asset.role+'.glb';file.textContent='下载 GLB ↓';const preview=document.createElement('a');preview.href='models.html?asset='+encodeURIComponent(asset.id);preview.target='_blank';preview.rel='noopener noreferrer';preview.textContent='旋转查看模型 ↗';links.append(preview,source,file);card.append(name,meta,links);$('asset-list').append(card);}}catch(error){$('asset-list').textContent='素材清单暂未加载，请刷新后重试。';console.error(error);}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)setPlaying(false);});
async function start(){zone('teams');setTime(3);try{const {VenueRenderer}=await import('./renderer-webgl.js');renderer=new VenueRenderer($('venue'),{onSelect:zone,onStatus:modelStatus});renderer.setFlows(true);renderer.setPlaying(false);setView('walk');zone('teams');currentPhase=-1;setTime(3);await renderer.ready;requestAnimationFrame(tick);}catch(error){modelStatus({state:'error'});console.error(error);}}
showAssetSources();start();
