import { validateModel,packGltf } from '../supabase/functions/_shared/models.ts';
import { tetrahedron } from '../tests/model-fixture.ts';
import { createApi } from '../supabase/functions/_shared/api.ts';
import type { Backend } from '../supabase/functions/_shared/backend.ts';
const fixture=tetrahedron();
const result=await validateModel(packGltf(fixture.json,fixture.resources));
if(result.triangles!==4) throw new Error('GLB validation failed');
const unused=()=>Promise.reject(new Error('health must not access backend'));
const backend:Backend={user:unused,scene:unused,jobs:unused,sign:unused,upload:unused};
const response=await createApi(backend,()=>undefined)(new Request('http://localhost/scene-api/health'));
if(response.status!==200) throw new Error('API startup failed');
console.log('Deno runtime: API health and Khronos GLB validator passed.');
